#main.py

from dotenv import load_dotenv
load_dotenv()

import os
import logging
import time
import requests
from flask import Flask, jsonify, request
from flask_cors import CORS

from firestore import (
    get_product_from_db,
    save_product_to_db,
    get_ingredient_profile_from_db,
    save_ingredient_to_db,
    save_percent_estimate_to_db,
    save_product_rating_to_db,
    get_recent_products,
)
from services.percent_estimate import get_percent_estimates

logging.basicConfig(level=logging.INFO)
logger = logging.getLogger(__name__)

app = Flask(__name__)
CORS(app)

# ─── Mode selection ───────────────────────────────────────────────────────────

ANALYSIS_MODE = os.getenv("ANALYSIS_MODE", "ml").lower()

if ANALYSIS_MODE == "groq":
    from utils.llm_client import get_ingredient_profile_from_llm, get_product_rating_from_llm
    logger.info("Analysis mode: GROQ (LLM-based ingredient profiles + rating)")
else:
    from ml.predict import predict_score, get_model_metadata
    logger.info("Analysis mode: ML (local GradientBoosting model)")


# ─── Helpers ──────────────────────────────────────────────────────────────────

def _flatten_ingredients(raw_list: list) -> list[str]:
    """Normalise a mixed list of strings / dicts to plain lowercase strings."""
    result = []
    for item in raw_list:
        if isinstance(item, dict):
            name = item.get("text") or item.get("name") or ""
        else:
            name = str(item)
        name = name.strip().lower()
        if name:
            result.append(name)
    return result


def _build_ingredient_profile_fallback(name: str) -> dict:
    """
    Rule-based ingredient profile matching the Gemini/Groq Firestore shape.
    Used in ML mode (no LLM calls) and as a fallback if Groq fails.
    """
    return {
        "ingredient_name": name,
        "ingredient_profile": {
            "health_score":      5,
            "pros":              [],
            "cons":              [],
            "allergen":          "unknown",
            "regulatory_status": "unknown",
            "category":          "other",
            "health_flag":       "unknown",
            "source":            "rule_based",
            "description":       "",
            "dietary_tags":      [],
            "flags":             [],
            "processing_level":  "unknown",
            "why_this_score":    "No profile available — rule-based fallback.",
        },
    }


def _fix_nested_profile(profile: dict) -> dict:
    """Fix double-nested ingredient profiles from old Gemini saves in Firestore."""
    if not profile:
        return profile
    inner = profile.get("ingredient_profile", {})
    if isinstance(inner, dict) and "ingredient_profile" in inner:
        profile["ingredient_profile"] = inner["ingredient_profile"]
    return profile


def _build_ml_rating_response(rating: dict) -> dict:
    """
    Wraps ML predict_score output into the dual schema:
      - Old frontend keys: product_score, processing_level, pros, cons
      - New ML keys:       overall_score, method, confidence, breakdown
    """
    score      = rating.get("overall_score", 0)
    breakdown  = rating.get("breakdown", {})
    method     = rating.get("method", "rule_based")
    confidence = rating.get("confidence", "medium")

    grade = _score_to_grade(score)

    return {
        # Old keys — frontend keeps working without changes
        "product_score":    round(score, 2),
        "processing_level": grade,
        "why_this_score":   (
            f"Score generated by ML model (method: {method}, confidence: {confidence})."
        ),
        "pros":             breakdown.get("positives", []),
        "cons":             breakdown.get("negatives", []),
        "dietary_tags":     [],

        # New ML keys
        "overall_score":    round(score, 2),
        "method":           method,
        "confidence":       confidence,
        "breakdown":        breakdown,
    }


def _build_groq_rating_response(rating: dict) -> dict:
    """
    Wraps Groq LLM rating output into the same dual schema.
    Groq returns: { product_score, processing_level, pros, cons,
                    why_this_score, dietary_tags, ... }
    """
    if "error" in rating:
        logger.warning("Groq rating error: %s", rating["error"])
        # Degrade gracefully to a neutral score
        return _build_ml_rating_response({"overall_score": 5.0, "method": "groq_error"})

    score = float(rating.get("product_score", rating.get("overall_score", 5.0)))

    return {
        # Old keys
        "product_score":    round(score, 2),
        "processing_level": rating.get("processing_level", _score_to_grade(score)),
        "why_this_score":   rating.get("why_this_score", ""),
        "pros":             rating.get("pros", []),
        "cons":             rating.get("cons", []),
        "dietary_tags":     rating.get("dietary_tags", []),

        # New keys — normalised so both modes share the same shape
        "overall_score":    round(score, 2),
        "method":           "groq",
        "confidence":       "high",
        "breakdown":        {
            "positives": rating.get("pros", []),
            "negatives": rating.get("cons", []),
        },
    }


def _score_to_grade(score: float) -> str:
    if score >= 8:   return "A"
    if score >= 6:   return "B"
    if score >= 4:   return "C"
    if score >= 2:   return "D"
    return "F"


# ─── Mode-aware scoring functions ─────────────────────────────────────────────

def _fetch_ingredient_profile(name: str) -> dict:
    """
    Returns a Firestore-ready profile dict.
    Groq mode  → LLM call → fallback on error
    ML mode    → rule-based fallback (profiles stored for consistency)
    """
    if ANALYSIS_MODE == "groq":
        try:
            llm_profile = get_ingredient_profile_from_llm(name)
            if llm_profile and "error" not in llm_profile:
                full_doc = {
                    "ingredient_name":    name,
                    "ingredient_profile": llm_profile,
                }
                save_ingredient_to_db(name, full_doc)
                return full_doc
        except Exception as e:
            logger.warning("Groq ingredient profile failed for '%s': %s", name, e)

    # ML mode or Groq fallback
    profile = _build_ingredient_profile_fallback(name)
    save_ingredient_to_db(name, profile)
    return profile


def _compute_rating(product_for_scoring: dict, final_ingredient_list: list,
                    percent_estimates: list) -> dict:
    """
    Returns the dual-schema rating dict.
    Groq mode → LLM call
    ML mode   → local GradientBoosting
    """
    if ANALYSIS_MODE == "groq":
        raw = get_product_rating_from_llm(final_ingredient_list, percent_estimates)
        return _build_groq_rating_response(raw)
    else:
        raw = predict_score(product_for_scoring)
        return _build_ml_rating_response(raw)


# ─── Main route ───────────────────────────────────────────────────────────────

@app.route("/get-complete-product-info", methods=["GET"])
def get_complete_product_info():
    barcode = request.args.get("barcode")
    if not barcode:
        return jsonify({"error": "No barcode provided"}), 400

    product_data   = get_product_from_db(barcode)
    nutrition_data = {}

    # ── Full cache hit: has rating + nutrients ────────────────────────────────
    if (product_data
            and product_data.get("product_rating")
            and product_data.get("nutrients_per_100g")):

        logger.info("Full cache hit for %s", barcode)

        ingredient_names      = _flatten_ingredients(product_data["ingredients"])
        final_ingredient_list = []
        for name in ingredient_names:
            profile = get_ingredient_profile_from_db(name)
            if not profile:
                profile = _build_ingredient_profile_fallback(name)
            final_ingredient_list.append({"name": name, "profile": _fix_nested_profile(profile)})

        return jsonify({
            "product_name":        product_data["product_name"],
            "ingredients_profile": final_ingredient_list,
            "nutrients":           product_data["nutrients_per_100g"],
            "percent_estimate":    product_data.get("percent_estimate", []),
            "overall_rating":      _build_rating_response_from_cache(product_data["product_rating"]),
            "cached":              True,
            "analysis_mode":       ANALYSIS_MODE,
        })

    # ── Partial cache: has product but no rating ──────────────────────────────
    if product_data and product_data.get("nutrients_per_100g"):
        logger.info("Partial cache hit for %s — running %s scorer", barcode, ANALYSIS_MODE)
        product_name     = product_data["product_name"]
        ingredient_names = _flatten_ingredients(product_data["ingredients"])
        nutrition_data   = product_data["nutrients_per_100g"]

    else:
        # ── Cache miss: fetch from OpenFoodFacts ──────────────────────────────
        logger.info("Cache miss — fetching from OpenFoodFacts for %s", barcode)

        url     = f"https://world.openfoodfacts.org/api/v0/product/{barcode}.json"
        headers = {"User-Agent": "TrueCheck-App/1.0 (student project)"}

        MAX_RETRIES  = 3
        RETRY_DELAYS = [3, 8, 20]
        resp         = None

        for attempt, delay in enumerate(RETRY_DELAYS):
            try:
                resp = requests.get(url, headers=headers, timeout=10)
                logger.info("OFf attempt %d — status: %d", attempt + 1, resp.status_code)

                if resp.status_code == 200:
                    break

                if resp.status_code == 429:
                    if attempt < MAX_RETRIES - 1:
                        logger.warning("OFf rate limited. Waiting %ds ...", delay)
                        time.sleep(delay)
                        continue
                    return jsonify({
                        "error": "OpenFoodFacts rate limit reached after retries.",
                        "tip":   "Scan again in a minute — first scan is always cached.",
                    }), 429

                return jsonify({"error": f"OpenFoodFacts error {resp.status_code}"}), 500

            except requests.exceptions.Timeout:
                logger.warning("OFf timeout on attempt %d", attempt + 1)
                if attempt < MAX_RETRIES - 1:
                    time.sleep(delay)
                else:
                    return jsonify({"error": "OpenFoodFacts timed out after retries."}), 504
            except Exception as e:
                logger.exception("Unexpected error fetching from OpenFoodFacts")
                return jsonify({"error": str(e)}), 500

        try:
            product = resp.json().get("product", {})
            if not product:
                return jsonify({
                    "error":   "Product not found",
                    "message": "This barcode is not in the OpenFoodFacts database.",
                    "barcode": barcode,
                }), 404

            product_name     = product.get("product_name", "Unknown")
            raw_ingredients  = [
                i.get("text") for i in product.get("ingredients", []) if "text" in i
            ]
            ingredient_names = _flatten_ingredients(raw_ingredients)
            nutriments       = product.get("nutriments", {})
            nutrition_data   = {k: v for k, v in nutriments.items() if k.endswith("_100g")}

            if not nutrition_data and not ingredient_names:
                return jsonify({
                    "error":        "No food data found",
                    "message":      "This may not be a food product.",
                    "product_name": product_name,
                }), 404

            save_product_to_db(barcode, product_name, ingredient_names, nutrition_data)

        except Exception as e:
            logger.exception("Failed to parse OpenFoodFacts response")
            return jsonify({"error": str(e)}), 500

    # ── Ingredient profiles ───────────────────────────────────────────────────
    final_ingredient_list = []
    for name in _flatten_ingredients(ingredient_names):
        profile = get_ingredient_profile_from_db(name)
        if not profile:
            profile = _fetch_ingredient_profile(name)   # mode-aware
        final_ingredient_list.append({"name": name, "profile": _fix_nested_profile(profile)})

    # ── Percent estimate ──────────────────────────────────────────────────────
    percent_estimates = get_percent_estimates(barcode, ingredient_names)

    # ── Rating ────────────────────────────────────────────────────────────────
    product_for_scoring = {
        "ingredients":        ingredient_names,
        "nutrients_per_100g": nutrition_data,
    }
    rating_response = _compute_rating(product_for_scoring, final_ingredient_list, percent_estimates)

    # ── Persist ───────────────────────────────────────────────────────────────
    # Store the raw dict (before schema wrapping) so cache rebuilds correctly
    raw_rating_to_store = {
        "overall_score": rating_response["overall_score"],
        "method":        rating_response["method"],
        "confidence":    rating_response.get("confidence", "medium"),
        "breakdown":     rating_response.get("breakdown", {}),
    }
    save_product_rating_to_db(barcode, raw_rating_to_store)
    save_percent_estimate_to_db(barcode, percent_estimates)

    return jsonify({
        "product_name":        product_name,
        "ingredients_profile": final_ingredient_list,
        "nutrients":           nutrition_data,
        "percent_estimate":    percent_estimates,
        "overall_rating":      rating_response,
        "cached":              False,
        "analysis_mode":       ANALYSIS_MODE,
    })


def _build_rating_response_from_cache(cached_rating: dict) -> dict:
    """
    Rebuild the dual-schema response from a cached raw rating dict.
    Works regardless of which mode generated it (groq or ml).
    """
    method = cached_rating.get("method", "unknown")
    if method == "groq":
        return _build_groq_rating_response({
            "product_score": cached_rating.get("overall_score", 5.0),
            "pros":          cached_rating.get("breakdown", {}).get("positives", []),
            "cons":          cached_rating.get("breakdown", {}).get("negatives", []),
        })
    return _build_ml_rating_response(cached_rating)


# ─── Utility routes ───────────────────────────────────────────────────────────

@app.route("/get-product-details", methods=["GET"])
def get_product_details():
    barcode = request.args.get("barcode")
    if not barcode:
        return jsonify({"error": "No barcode provided"}), 400

    product_data = get_product_from_db(barcode)
    if product_data:
        return jsonify({
            "product_name":    product_data.get("product_name", "Unknown"),
            "ingredients":     product_data.get("ingredients", []),
            "nutrients_per_100g": product_data.get("nutrients_per_100g", {}),
        })

    url      = f"https://world.openfoodfacts.org/api/v0/product/{barcode}.json"
    response = requests.get(url, timeout=10)
    if response.status_code != 200:
        return jsonify({"error": "Failed to fetch from OpenFoodFacts"}), 500

    product      = response.json().get("product", {})
    product_name = product.get("product_name", "Unknown")
    ingredients  = [i.get("text") for i in product.get("ingredients", []) if "text" in i]
    nutriments   = product.get("nutriments", {})
    nutrition    = {k: v for k, v in nutriments.items() if k.endswith("_100g")}

    save_product_to_db(barcode, product_name, ingredients, nutrition)

    return jsonify({
        "product_name":       product_name,
        "ingredients":        ingredients,
        "nutrients_per_100g": nutrition,
    })


@app.route("/get-ingredients", methods=["GET"])
def get_ingredients():
    barcode = request.args.get("barcode")
    if not barcode:
        return jsonify({"error": "No barcode provided"}), 400

    product_data = get_product_from_db(barcode)
    if product_data:
        return jsonify({
            "product_name": product_data["product_name"],
            "ingredients":  product_data.get("ingredients", []),
        })

    url      = f"https://world.openfoodfacts.org/api/v0/product/{barcode}.json"
    response = requests.get(url, timeout=10)
    if response.status_code != 200:
        return jsonify({"error": "Failed to fetch from OpenFoodFacts"}), 500

    product      = response.json().get("product", {})
    product_name = product.get("product_name", "Unknown")
    ingredients  = [i.get("text") for i in product.get("ingredients", []) if "text" in i]

    if not ingredients:
        return jsonify({
            "product_name": product_name,
            "ingredients":  [],
            "note": "No ingredients found for this barcode on OpenFoodFacts.",
        })

    save_product_to_db(barcode, product_name, ingredients)
    return jsonify({"product_name": product_name, "ingredients": ingredients})


@app.route("/get-overall-product-rating", methods=["GET"])
def get_overall_product_rating():
    barcode = request.args.get("barcode")
    if not barcode:
        return jsonify({"error": "No barcode provided"}), 400

    product_data = get_product_from_db(barcode)
    if not product_data:
        return jsonify({"error": "Product not found in DB"}), 404

    ingredient_names = _flatten_ingredients(product_data.get("ingredients", []))
    if not ingredient_names:
        return jsonify({"error": "No ingredients found. Scan product first."}), 400

    final_ingredient_list = [
        {"name": n, "profile": get_ingredient_profile_from_db(n) or _build_ingredient_profile_fallback(n)}
        for n in ingredient_names
    ]
    percent_estimates = get_percent_estimates(barcode, ingredient_names)
    nutrition_data    = product_data.get("nutrients_per_100g", {})

    product_for_scoring = {
        "ingredients":        ingredient_names,
        "nutrients_per_100g": nutrition_data,
    }
    rating_response = _compute_rating(product_for_scoring, final_ingredient_list, percent_estimates)

    raw_rating_to_store = {
        "overall_score": rating_response["overall_score"],
        "method":        rating_response["method"],
        "confidence":    rating_response.get("confidence", "medium"),
        "breakdown":     rating_response.get("breakdown", {}),
    }
    save_product_rating_to_db(barcode, raw_rating_to_store)

    return jsonify(rating_response)


@app.route("/explore", methods=["GET"])
def explore():
    sort_by = request.args.get("sort", "recent")
    limit   = int(request.args.get("limit", 20))
    return jsonify(get_recent_products(limit=limit, sort_by=sort_by))


# ─── ML-only routes (no-op / 404 in groq mode) ───────────────────────────────

@app.route("/model-info", methods=["GET"])
def model_info():
    if ANALYSIS_MODE != "ml":
        return jsonify({"message": "model-info is only available in ML mode."}), 200
    meta = get_model_metadata()
    if meta:
        return jsonify(meta)
    return jsonify({
        "status":  "no model trained yet",
        "message": "Run: python -m ml.train",
    }), 404


@app.route("/retrain", methods=["POST"])
def retrain():
    if ANALYSIS_MODE != "ml":
        return jsonify({"message": "Retrain is only available in ML mode."}), 200
    try:
        from ml.train import train
        from ml.predict import _load_model
        result = train()
        _load_model()
        return jsonify({"status": "ok", "result": str(result)})
    except Exception as e:
        logger.exception("Manual retrain failed")
        return jsonify({"error": str(e)}), 500


# ─── Health check ─────────────────────────────────────────────────────────────

@app.route("/health", methods=["GET"])
def health():
    return jsonify({"status": "ok", "analysis_mode": ANALYSIS_MODE})


if __name__ == "__main__":
    app.run(debug=True)