"""
TrueCheck — Flask Backend
==========================
All Gemini/LLM dependencies removed.
Product scoring is handled by the local ML pipeline.
"""

from dotenv import load_dotenv
load_dotenv()

import os
import logging
import time
import requests
from flask import Flask, jsonify, request
from flask_cors import CORS

from firestore import (
    get_product_from_db,
    save_product_to_db,
    get_ingredient_profile_from_db,
    save_ingredient_to_db,
    save_percent_estimate_to_db,
    save_product_rating_to_db,
)
from ml.predict import predict_score, get_model_metadata
from ml.feature_engineering import extract_features, features_to_vector
from services.percent_estimate import get_percent_estimates

logging.basicConfig(level=logging.INFO)
logger = logging.getLogger(__name__)

app = Flask(__name__)
CORS(app)


# ─── Helpers ──────────────────────────────────────────────────────────────────

def _flatten_ingredients(raw_list: list) -> list:
    """Normalise a mixed list of strings / dicts to plain strings."""
    result = []
    for item in raw_list:
        if isinstance(item, dict):
            name = item.get("text") or item.get("name") or ""
        else:
            name = str(item)
        name = name.strip().lower()
        if name:
            result.append(name)
    return result


def _build_rating_response(rating: dict) -> dict:
    """
    Maps the ML rating dict to a shape that satisfies BOTH:
      - Old frontend schema: { product_score, pros, cons, dietary_tags,
                               processing_level, why_this_score }
      - New ML schema:       { overall_score, method, confidence, breakdown }

    This means the frontend keeps working without any changes,
    while new clients can also read the richer ML fields.
    """
    score     = rating.get("overall_score", 0)
    breakdown = rating.get("breakdown", {})
    method    = rating.get("method", "rule_based")
    confidence = rating.get("confidence", "medium")

    # Map 0-10 score to letter grade for legacy processing_level field
    if score >= 8:
        grade = "A"
    elif score >= 6:
        grade = "B"
    elif score >= 4:
        grade = "C"
    elif score >= 2:
        grade = "D"
    else:
        grade = "F"

    return {
        # ── Old keys — frontend keeps working without changes ─────────────────
        "product_score":     round(score, 2),
        "processing_level":  grade,
        "why_this_score":    (
            f"Score generated by ML model (method: {method}, "
            f"confidence: {confidence})."
        ),
        "pros":              breakdown.get("positives", []),
        "cons":              breakdown.get("negatives", []),
        "dietary_tags":      [],   # reserved for future use

        # ── New ML keys — richer data for updated frontend ────────────────────
        "overall_score":     round(score, 2),
        "method":            method,
        "confidence":        confidence,
        "breakdown":         breakdown,
    }


def _build_ingredient_profile_fallback(name: str) -> dict:
    """
    Rule-based fallback profile that matches the OLD Gemini profile shape
    so Firestore stays consistent across cached and new ingredients.
    """
    return {
    "ingredient_name": name,
    "ingredient_profile": {
        "health_score":       5,
        "pros":               [],
        "cons":               [],
        "allergen":           "unknown",
        "regulatory_status":  "unknown",
        "category":           "other",
        "health_flag":        "unknown",
        "source":             "rule_based",
        "description":        "",
        "dietary_tags":       [],
        "flags":              [],
        "processing_level":   "unknown",
        "why_this_score":     "No profile available — rule-based fallback.",
    },
}
def _fix_nested_profile(profile: dict) -> dict:
    """Fix double-nested ingredient profiles from old rule-based saves."""
    if not profile:
        return profile
    inner = profile.get("ingredient_profile", {})
    if isinstance(inner, dict) and "ingredient_profile" in inner:
        profile["ingredient_profile"] = inner["ingredient_profile"]
    return profile


# ─── Main route ───────────────────────────────────────────────────────────────

@app.route("/get-complete-product-info", methods=["GET"])
def get_complete_product_info():
    barcode = request.args.get("barcode")
    if not barcode:
        return jsonify({"error": "No barcode provided"}), 400

    product_data   = get_product_from_db(barcode)
    nutrition_data = {}

    # ── FIX #6: Early return if fully cached (skips ML re-run + DB write) ─────
    if (product_data
            and product_data.get("product_rating")
            and product_data.get("nutrients_per_100g")):

        logger.info("Full cache hit for %s — returning saved rating", barcode)

        ingredient_names      = _flatten_ingredients(product_data["ingredients"])
        final_ingredient_list = []
        for name in ingredient_names:
            profile = get_ingredient_profile_from_db(name)
            if not profile:
                profile = _build_ingredient_profile_fallback(name)
            final_ingredient_list.append({"name": name, "profile": _fix_nested_profile(profile)})

        return jsonify({
            "product_name":        product_data["product_name"],
            "ingredients_profile": final_ingredient_list,
            "nutrients":           product_data["nutrients_per_100g"],
            "percent_estimate":    product_data.get("percent_estimate", []),
            "overall_rating":      _build_rating_response(product_data["product_rating"]),
            "cached":              True,
        })

    # ── Partial cache: has nutrients but no rating yet ────────────────────────
    if product_data and product_data.get("nutrients_per_100g"):
        logger.info("Partial cache hit for %s — rating missing, running ML", barcode)
        product_name     = product_data["product_name"]
        ingredient_names = _flatten_ingredients(product_data["ingredients"])
        nutrition_data   = product_data["nutrients_per_100g"]

    else:
        # ── Full cache miss: fetch from OpenFoodFacts ─────────────────────────
        logger.info("Cache miss — fetching from OpenFoodFacts for %s", barcode)

        url     = f"https://world.openfoodfacts.org/api/v0/product/{barcode}.json"
        headers = {"User-Agent": "TrueCheck-App/1.0 (student project)"}

        MAX_RETRIES  = 3
        RETRY_DELAYS = [3, 8, 20]
        resp         = None

        for attempt, delay in enumerate(RETRY_DELAYS):
            try:
                resp = requests.get(url, headers=headers, timeout=10)
                logger.info("Attempt %d — status: %d", attempt + 1, resp.status_code)

                if resp.status_code == 200:
                    break

                if resp.status_code == 429:
                    if attempt < MAX_RETRIES - 1:
                        logger.warning("Rate limited. Waiting %ds ...", delay)
                        time.sleep(delay)
                        continue
                    return jsonify({
                        "error": "OpenFoodFacts rate limit reached after retries.",
                        "tip":   "Scan again in a minute — first scan is cached.",
                    }), 429

                return jsonify({"error": f"OpenFoodFacts error {resp.status_code}"}), 500

            except requests.exceptions.Timeout:
                logger.warning("Timeout on attempt %d", attempt + 1)
                if attempt < MAX_RETRIES - 1:
                    time.sleep(delay)
                else:
                    return jsonify({"error": "OpenFoodFacts timed out after retries."}), 504

            except Exception as e:
                logger.exception("Unexpected error fetching from OpenFoodFacts")
                return jsonify({"error": str(e)}), 500

        try:
            product = resp.json().get("product", {})

            if not product:
                return jsonify({
                    "error":   "Product not found",
                    "message": "This barcode is not in the OpenFoodFacts database.",
                    "barcode": barcode,
                }), 404

            product_name     = product.get("product_name", "Unknown")
            raw_ingredients  = [
                i.get("text") for i in product.get("ingredients", []) if "text" in i
            ]
            ingredient_names = _flatten_ingredients(raw_ingredients)
            nutriments       = product.get("nutriments", {})
            nutrition_data   = {k: v for k, v in nutriments.items() if k.endswith("_100g")}

            if not nutrition_data and not ingredient_names:
                return jsonify({
                    "error":        "No food data found",
                    "message":      "This may not be a food product.",
                    "product_name": product_name,
                }), 404

            save_product_to_db(barcode, product_name, ingredient_names, nutrition_data)

        except Exception as e:
            logger.exception("Failed to parse OpenFoodFacts response")
            return jsonify({"error": str(e)}), 500

    # ── Ingredient profiles ───────────────────────────────────────────────────
    ingredient_names      = _flatten_ingredients(ingredient_names)
    final_ingredient_list = []

    for name in ingredient_names:
        if not isinstance(name, str):
            continue
        profile = get_ingredient_profile_from_db(name)

        if not profile:
            # FIX #5: fallback matches old Gemini shape — Firestore stays consistent
            profile = _build_ingredient_profile_fallback(name)
            save_ingredient_to_db(name, name, profile)

        final_ingredient_list.append({"name": name, "profile": _fix_nested_profile(profile)})

    # ── Percent estimate ──────────────────────────────────────────────────────
    percent_estimates = get_percent_estimates(barcode, ingredient_names)

    # ── ML Prediction ─────────────────────────────────────────────────────────
    product_for_ml = {
        "ingredients":        ingredient_names,
        "nutrients_per_100g": nutrition_data,
    }

    rating          = predict_score(product_for_ml)
    rating_response = _build_rating_response(rating)  # FIX #3: schema wrapper

    # ── Save ──────────────────────────────────────────────────────────────────
    save_product_rating_to_db(barcode, rating)
    save_percent_estimate_to_db(barcode, percent_estimates)

    return jsonify({
        "product_name":        product_name,
        "ingredients_profile": final_ingredient_list,
        "nutrients":           nutrition_data,
        "percent_estimate":    percent_estimates,
        "overall_rating":      rating_response,
        "cached":              False,
    })


# ─── Model info ───────────────────────────────────────────────────────────────

@app.route("/model-info", methods=["GET"])
def model_info():
    meta = get_model_metadata()
    if meta:
        return jsonify(meta)
    return jsonify({
        "status":  "no model trained yet",
        "message": "Run: python -m ml.train",
    }), 404


# ─── Manual retrain trigger ───────────────────────────────────────────────────

@app.route("/retrain", methods=["POST"])
def retrain():
    """Manually trigger a model retrain. Useful after bulk importing products."""
    try:
        from ml.train import train
        from ml.predict import _load_model
        result = train()
        _load_model()   # hot-reload without restarting server
        return jsonify({"status": "ok", "result": str(result)})
    except Exception as e:
        logger.exception("Manual retrain failed")
        return jsonify({"error": str(e)}), 500


# ─── Health check ─────────────────────────────────────────────────────────────

@app.route("/health", methods=["GET"])
def health():
    return jsonify({"status": "ok"})


# ─── Run ──────────────────────────────────────────────────────────────────────

if __name__ == "__main__":
    app.run(debug=True)
